//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sevices7122020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public string maLop { get; set; }
        public string tenLop { get; set; }
        public string khoaHoc { get; set; }
        public string maGVCN { get; set; }
        public string khoa { get; set; }
        public string chuyenNghanh { get; set; }
        public Nullable<int> soLuongSinhVien { get; set; }
        public Nullable<int> nienKhoa { get; set; }
    }
}
