//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sevices7122020
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhvien_lop
    {
        public string maMonHoc { get; set; }
        public string masv { get; set; }
        public string phongHoc { get; set; }
        public Nullable<System.DateTime> thoiDiemBatDau { get; set; }
        public Nullable<System.DateTime> thoiDiemKetThuc { get; set; }
    }
}
