//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sevices7122020
{
    using System;
    using System.Collections.Generic;
    
    public partial class monHoc
    {
        public string maMonHoc { get; set; }
        public string tenMon { get; set; }
        public string maMonTienQuyet { get; set; }
        public Nullable<int> kyHoc { get; set; }
        public Nullable<int> soTinChi { get; set; }
        public Nullable<int> soTietLyThuyet { get; set; }
        public Nullable<int> soTietThucHanh { get; set; }
        public Nullable<byte> monTuChon { get; set; }
        public Nullable<byte> monChungChi { get; set; }
    }
}
