//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sevices7122020
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhvien
    {
        public string masv { get; set; }
        public string hotensv { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string diachi { get; set; }
        public Nullable<int> sdt { get; set; }
        public string email { get; set; }
        public Nullable<byte> trangthai { get; set; }
    }
}
